# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10
